

<div class="z-depth-1 grey lighten-4 row" style="padding: 30px;">
  <div class="container">
    <h3>USUARIOS</h3>
    <?php
      if(isset($_GET['success']))
      {
        if($_GET['success'] == 1)
        {
          echo 'Usuário deletado';
        }
        else {
          echo 'Erro ao excluir usuário';
        }
      }
    ?>

    <table class="table">
        <thead>
          <tr>
            <th><a class="btn btn-primary" href="form-usuario.php" style="margin-right: 30px;">Novo</a></th>
            <th>NOME</th>
            <th>EMAIL</th>
            <th>OBRAS</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <?php foreach($this->view->usuarios as $usuario): ?>
            <td style="margin-right: 30px;" > 
                <a href="../../model/Usuario/deleta_usuario.php?id=<?php echo $usuario['id']?>" class="btn-floating btn-small waves-effect waves-light red right"><i class="material-icons">delete</i></a>
                <a href="form-usuario.php?id=<?php echo $usuario['id']?>" class="btn-floating btn-small waves-effect waves-light red right"><i class="material-icons">edit</i></a>
            </td>
            <td><?php print_r($usuario['nome']) ?></td>
            <td><?php print_r($usuario['email']) ?></td>
            <td><?php print_r(implode(', ' , $usuario['obra'])); ?></td>
          </tr>
            <?php endforeach; ?>
        </tbody>
      </table>
  </div>
</div>